name: Check
on: push 
jobs: 
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello Padlo!
      - name: Print lines
        run: |
          echo first line
          echo second line
