name: Check
on: push 
jobs: 
  lint: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: npm ci 
      - name: Link
        run: npm run lint
        